opencl: remove a self-referential macro
PoCL fails to compile due to a self-referential macro in
ggml-opencl_mm.cl (`#define sub_group_reduce_add
sub_group_reduce_add`) on some devices:

```
error: /home/linehill/.cache/pocl/kcache/tempfile_qlSuTg.cl:1048:11 <Spelling=/home/linehill/.cache/pocl/kcache/tempfile_qlSuTg.cl:851:30>: use of undeclared identifier 'sub_group_reduce_add'
...
```